# Generated by Django 3.2 on 2021-04-29 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210429_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 7, 21, 789067)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='location',
            field=models.CharField(choices=[('SA', 'Saudi Arabia'), ('FR', 'Out of Saudi Arabia'), ('NA', 'Prefer not to say')], default='Prefer not to say', max_length=250),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 7, 21, 789067)),
        ),
    ]
