# Generated by Django 3.2 on 2021-05-03 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210429_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 837940))),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 837940))),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 836942)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 836942)),
        ),
    ]
