# Generated by Django 3.2 on 2021-05-03 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_auto_20210503_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 842926))),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 16, 11, 842926))),
                ('title', models.CharField(max_length=800)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
