# Generated by Django 3.2 on 2021-05-03 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 23, 54, 941594)),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 23, 54, 941594)),
        ),
    ]
